FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR "/src"
COPY ["Coodesh.Back.End.Challenge2021.CSharp.sln", "./"]
COPY *.config .
COPY ["Core/Coodesh.Back.End.Challenge2021.CSharp.Core.csproj", "Core/"]
COPY ["Api/Coodesh.Back.End.Challenge2021.CSharp.Api.csproj", "Api/"]
COPY ["Cron/Coodesh.Back.End.Challenge2021.CSharp.Cron.csproj", "Cron/"]

RUN dotnet restore --disable-parallel --configfile ./nuget.config
COPY . .

WORKDIR "/src/Core"
RUN dotnet build -c Release -o /app

WORKDIR "/src/Api"
RUN dotnet build -c Release -o /app

WORKDIR "/src/Cron"
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

# Fix from:
# https://github.com/bringnow/docker-letsencrypt-manager/commit/7a157dcd05ea8e745ec604734f6e7aa2e9e7b7cc
# Put cron logfiles into a volume. This also works around bug
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810669
# caused by base image using old version of coreutils
# which causes "tail: unrecognized file system type 0x794c7630 for '/var/log/cron.log'"
# when using docker with overlay storage driver.
VOLUME /var/log/

#ADD *.sh /root/
#RUN chmod 750 /root/cron_task.sh
#RUN chmod 750 /root/run_redditbot.sh
#RUN chmod 750 /app/

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
RUN apt-get update
RUN apt-get install -y cron
COPY --from=publish /app/*.sh /root/
RUN chmod 750 /app/cron_task.sh
#RUN chmod 750 /root/run_redditbot.sh
RUN chmod 750 /app/
RUN mkdir /var/spool/cron/crontabs/root 
COPY --from=publish /app/crontab /var/spool/cron/crontabs/root
RUN chmod 0600 /var/spool/cron/crontabs/root
#CMD touch /var/log/cron.log && cron && env > /root/env.sh && tail -f /var/log/cron.log
ENTRYPOINT ["dotnet", "Coodesh.Back.End.Challenge2021.CSharp.Api.dll"]

#CMD touch /var/log/cron.log && cron && env > /root/env.sh && tail -f /var/log/cron.log